### ISSUE TITLE
Version Update Request - Ubooquity 3

### ISSUE THREAD

**Issue by hzielke** [linuxserver/docker-ubooquity#47]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

A new version of Ubooquity is has finally arrived:
https://vaemendis.net/ubooquity/article23/ubooquity-3-beta
New requirement is Java 17.

Would it be possible to update the docker?

### Reason for change

Version update with new java requirement

**Comment by thespad** [comment]
Once there's a stable release we'll pick it up and build, I'll get a PR ready to update the Java deps for when that happens.

**Comment by pieisround** [comment]
I don't know if I should post here or create a separate issue for this. But after updating the docker I'm now getting errors while reading files that I believe is related to going from jdk-base to jdk-headless. As the program requires several image extensions to operate. Adding libjavajpeg.so to the lib directory solves many of the scanning issues but I'm still seeing several others related to color pallets. Below is the original error.

` ERROR com.ubooquity.data.feeder.a - Failed to insert /FILENAME
java.lang.NoClassDefFoundError: Could not initialize class com.sun.imageio.plugins.jpeg.JPEGImageReader
   at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:85) ~[na:na]
   at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderSpi.createReaderInstance(JPEGImageReaderSpi.java:126) ~[imageio-jpeg-3.3.1.jar.10613186102461637445.tmp:3.3.1]
   at java.desktop/javax.imageio.spi.ImageReaderSpi.createReaderInstance(ImageReaderSpi.java:320) ~[na:na]
   at java.desktop/javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:534) ~[na:na]
   at java.desktop/javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:518) ~[na:na]
   at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1465) ~[na:na]
   at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1365) ~[na:na]
   at com.ubooquity.fileformat.cbr.a.a(SourceFile:84) ~[Ubooquity.jar:2.1.2]
   at com.ubooquity.f.a.a(SourceFile:38) ~[Ubooquity.jar:2.1.2]
   at com.ubooquity.data.feeder.b.a(SourceFile:63) ~[Ubooquity.jar:2.1.2]
   at com.ubooquity.data.feeder.a.b(SourceFile:554) ~[Ubooquity.jar:2.1.2]
   at com.ubooquity.data.feeder.a.b(SourceFile:468) ~[Ubooquity.jar:2.1.2]
   at com.ubooquity.data.feeder.a.b(SourceFile:112) ~[Ubooquity.jar:2.1.2]
   at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: no javajpeg in system library path: /usr/lib/jvm/java-17-openjdk/lib [in thread "Scanner thread"]
   at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2408) ~[na:na]
   at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818) ~[na:na]
   at java.base/java.lang.System.loadLibrary(System.java:1989) ~[na:na]
   at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader$1.run(JPEGImageReader.java:99) ~[na:na]
   at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader$1.run(JPEGImageReader.java:96) ~[na:na]
   at java.base/java.security.AccessController.doPrivileged(AccessController.java:318) ~[na:na]
   at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.initStatic(JPEGImageReader.java:95) ~[na:na]
   at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.(JPEGImageReader.java:90) ~[na:na]
... 14 common frames omitted`

**Comment by thespad** [comment]
Ugh, apparently openjdk8-jre-base (No GUI support) is fundamentally different from the later JRE headless packages. I'll open a PR to install the full JRE package.

**Comment by thespad** [comment]
Resolved by https://github.com/linuxserver/docker-ubooquity/pull/49
