### ISSUE TITLE
[BUG] Cannot access any content from home anymore

### ISSUE THREAD

**Issue by janaxhell** [linuxserver/docker-ubooquity#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I haven't used Ubooquity for a few months, but it was always running and getting updated by Watchtower on my server. yesterday I opened it and while I could reach the homepage, any content link like Books or Comics leads me to 

```
HTTP ERROR 500
Problem accessing /ubooquity/comics/. Reason:

    Internal server error: Cannot invoke "java.util.List.iterator()" because "<parameter2>" is null
[Powered by Jetty:// 9.4.0.v20161208](http://eclipse.org/jetty)
```

### Expected Behavior

It worked fine before, I expect to be able to browse my books and comics.

### Steps To Reproduce

1. Open Ubooquity
2. Browse Comics or Books

### Environment

```markdown
- OS: Open Media Vault 6
- How docker service was installed: from OMV6
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  ubooquity:
    image: lscr.io/linuxserver/ubooquity:latest
    container_name: ubooquity
    environment:
      - PUID=998
      - PGID=100
      - TZ=Etc/UTC
      - MAXMEM=2048
    volumes:
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Ubooquity:/config
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/books:/books
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/comics:/comics
      # - /path/to/comics:/comics
      # - /path/to/raw/files:/files
    ports:
      - 2202:2202
      - 2203:2203
    restart: unless-stopped
```

### Container logs

```bash
This is a snippet of what's repeating over and over for all comics and books. 

20240111 13:32:13 [Scanner thread] INFO  com.ubooquity.b.d - Reading metadata of comic file: /comics/Italia/- Magazines Comics/Corto Maltese/Corto Maltese 006 - Anno 02x03.cbz
20240111 13:32:13 [Scanner thread] INFO  com.ubooquity.data.database.c - Inserting/updating comic entry in database : /comics/Italia/- Magazines Comics/Corto Maltese/Corto Maltese 006 - Anno 02x03.cbz
20240111 13:32:17 [Scanner thread] INFO  com.ubooquity.b.d - Reading metadata of comic file: /comics/Italia/- Magazines Comics/Corto Maltese/Corto Maltese 020 - Anno 03x05.cbz
20240111 13:32:17 [Scanner thread] INFO  com.ubooquity.data.database.c - Inserting/updating comic entry in database : /comics/Italia/- Magazines Comics/Corto Maltese/Corto Maltese 020 - Anno 03x05.cbz
20240111 13:32:17 [Scanner thread] ERROR com.ubooquity.data.database.c - Error while creating/updating comic in database
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.message.DbException.get(DbException.java:144) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.engine.Session.getTransaction(Session.java:1611) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1621) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.engine.Session.setSavepoint(Session.java:800) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.command.Command.executeUpdate(Command.java:252) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.jdbc.JdbcConnection.rollbackInternal(JdbcConnection.java:1515) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:499) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.jdbcx.JdbcXAConnection.getConnection(JdbcXAConnection.java:104) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:197) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at com.ubooquity.data.database.c.a(SourceFile:615) ~[Ubooquity.jar:2.1.2]
	at com.ubooquity.data.database.c.a(SourceFile:68) ~[Ubooquity.jar:2.1.2]
	at com.ubooquity.data.feeder.a.b(SourceFile:548) ~[Ubooquity.jar:2.1.2]
	at com.ubooquity.data.feeder.a.b(SourceFile:468) ~[Ubooquity.jar:2.1.2]
	at com.ubooquity.data.feeder.a.b(SourceFile:112) ~[Ubooquity.jar:2.1.2]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
20240111 13:32:17 [Scanner thread] INFO  com.ubooquity.b.d - Reading metadata of comic file: /comics/Italia/- Magazines Comics/Corto Maltese/Corto Maltese 034 - Anno 04x07.cbz
20240111 13:32:18 [Scanner thread] INFO  com.ubooquity.data.database.c - Inserting/updating comic entry in database : /comics/Italia/- Magazines Comics/Corto Maltese/Corto Maltese 034 - Anno 04x07.cbz
20240111 13:32:22 [Scanner thread] INFO  com.ubooquity.b.d - Reading metadata of comic file: /comics/Italia/- Magazines Comics/Corto Maltese/Corto Maltese 048 - Anno 05x09.cbz
20240111 13:32:23 [Scanner thread] INFO  com.ubooquity.data.database.c - Inserting/updating comic entry in database : /comics/Italia/- Magazines Comics/Corto Maltese/Corto Maltese 048 - Anno 05x09.cbz
20240111 13:32:23 [Scanner thread] ERROR com.ubooquity.data.database.c - Error while creating/updating comic in database
org.h2.jdbc.JdbcSQLException: The database has been closed [90098-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.message.DbException.get(DbException.java:144) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.engine.Session.getTransaction(Session.java:1611) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.engine.Session.getStatementSavepoint(Session.java:1621) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.engine.Session.setSavepoint(Session.java:800) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.command.Command.executeUpdate(Command.java:252) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.jdbc.JdbcConnection.rollbackInternal(JdbcConnection.java:1515) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:499) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.jdbcx.JdbcXAConnection.getConnection(JdbcXAConnection.java:104) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:197) ~[h2-1.4.193.jar.215347347804627969.tmp:1.4.193]
	at com.ubooquity.data.database.c.a(SourceFile:615) ~[Ubooquity.jar:2.1.2]
	at com.ubooquity.data.database.c.a(SourceFile:68) ~[Ubooquity.jar:2.1.2]
	at com.ubooquity.data.feeder.a.b(SourceFile:548) ~[Ubooquity.jar:2.1.2]
	at com.ubooquity.data.feeder.a.b(SourceFile:468) ~[Ubooquity.jar:2.1.2]
	at com.ubooquity.data.feeder.a.b(SourceFile:112) ~[Ubooquity.jar:2.1.2]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
```

**Comment by j0nnymoe** [comment]
Looks like a corrupted database, not surprised it's happened if you run watchtower. Try restoring a backup.

**Comment by janaxhell** [comment]
I see. I don't have a backup, never needed, Watchtower never broke any other dbase. I'll rescan from scratch.
