### ISSUE TITLE
ubooquity:latest gives error on attempting to login, ubooquity:23 working

### ISSUE THREAD

**Issue by CHBMB** [linuxserver/docker-ubooquity#8]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

 Unraid

`docker run -d --name="ubooquity" --net="bridge" -e TZ="Europe/London" -e HOST_OS="unRAID" -e "MAXMEM"="512" -e "PUID"="99" -e "PGID"="100" -p 2202:2202/tcp -v "/mnt/user/books/":"/books":ro -v "/mnt/user/comics/":"/comics":ro -v "/mnt/cache/.appdata/ubooquity-test":"/config":rw linuxserver/ubooquity`

```20170326 10:54:10 [pool-1-thread-6] ERROR com.ubooquity.Ubooquity - Uncaught exception on thread: pool-1-thread-6
java.lang.NoClassDefFoundError: Could not initialize class sun.security.ec.SunEC
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_121]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_121]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_121]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_121]
at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_121]
at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:221) ~[na:1.8.0_121]
at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206) ~[na:1.8.0_121]
at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206) ~[na:1.8.0_121]
at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187) ~[na:1.8.0_121]
at sun.security.jca.ProviderList.getProvider(ProviderList.java:233) ~[na:1.8.0_121]
at sun.security.jca.ProviderList$ServiceList.tryGet(ProviderList.java:434) ~[na:1.8.0_121]
at sun.security.jca.ProviderList$ServiceList.access$200(ProviderList.java:376) ~[na:1.8.0_121]
at sun.security.jca.ProviderList$ServiceList$1.hasNext(ProviderList.java:486) ~[na:1.8.0_121]
at javax.crypto.Mac.getInstance(Mac.java:174) ~[na:1.8.0_121]
at com.ubooquity.f.c.a(SourceFile:29) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.provider.webadmin.j.a(SourceFile:600) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.provider.webadmin.j.a(SourceFile:115) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.c.a(SourceFile:324) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.c.a(SourceFile:58) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.c$1.a(SourceFile:133) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.e.e.a(SourceFile:287) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.e.e$f.a(SourceFile:830) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.e.e$1$1.run(SourceFile:210) ~[Ubooquity.jar:1.10.1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
20170326 10:48:20 [pool-1-thread-2] ERROR com.ubooquity.Ubooquity - Uncaught exception on thread: pool-1-thread-2
java.lang.InternalError: null
at sun.security.ec.SunEC.initialize(Native Method) ~[sunec.jar:1.8.0_121]
at sun.security.ec.SunEC.access$000(SunEC.java:49) ~[sunec.jar:1.8.0_121]
at sun.security.ec.SunEC$1.run(SunEC.java:61) ~[sunec.jar:1.8.0_121]
at sun.security.ec.SunEC$1.run(SunEC.java:58) ~[sunec.jar:1.8.0_121]
at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
at sun.security.ec.SunEC.<clinit>(SunEC.java:58) ~[sunec.jar:1.8.0_121]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_121]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_121]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_121]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_121]
at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_121]
at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:221) ~[na:1.8.0_121]
at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206) ~[na:1.8.0_121]
at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206) ~[na:1.8.0_121]
at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187) ~[na:1.8.0_121]
at sun.security.jca.ProviderList.getProvider(ProviderList.java:233) ~[na:1.8.0_121]
at sun.security.jca.ProviderList$ServiceList.tryGet(ProviderList.java:434) ~[na:1.8.0_121]
at sun.security.jca.ProviderList$ServiceList.access$200(ProviderList.java:376) ~[na:1.8.0_121]
at sun.security.jca.ProviderList$ServiceList$1.hasNext(ProviderList.java:486) ~[na:1.8.0_121]
at javax.crypto.Mac.getInstance(Mac.java:174) ~[na:1.8.0_121]
at com.ubooquity.f.c.a(SourceFile:29) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.provider.webadmin.j.a(SourceFile:600) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.provider.webadmin.j.a(SourceFile:115) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.c.a(SourceFile:324) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.c.a(SourceFile:58) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.c$1.a(SourceFile:133) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.e.e.a(SourceFile:287) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.e.e$f.a(SourceFile:830) ~[Ubooquity.jar:1.10.1]
at com.ubooquity.e.e$1$1.run(SourceFile:210) ~[Ubooquity.jar:1.10.1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_121]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_121]
at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
```
How to reproduce

 Pull container:latest (24)
 Set admin password
 Log out admin
 Attempt to log back in, gives error in Chrome
```
This page isn’t working

192.168.0.1 didn’t send any data.
ERR_EMPTY_RESPONSE
```

Fixed by rolling back to `linuxserver/ubooquity:23`

**Comment by zaggash** [comment]
I go the same issue.
